[project]
name = "lab-tic-tac-toe-game"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "websockets>=15.0.1",
]
